# Generated by Django 4.2.3 on 2023-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='fotos')),
                ('depoimento', models.TextField(max_length=500)),
            ],
        ),
    ]
